name: "[Appetizer] - Release Hack"
on:
  push:
    tags:
      - '**'
    branches:
      - main
    paths:
      - "services/appetizer/**"
  pull_request:
    branches: ["**"]
    paths:
      - "services/appetizer/**"
env:
  AWS_REGION: eu-central-1

jobs:
  build:
#    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      #- name: Update app version from configuration
      #  working-directory: ./
      #  run: |
      #    cp ./script/version_updater.sh ./version_updater.sh
      #    sh version_updater.sh

      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: service_account_json_file
        with:
          fileName: "serviceAccount.json"
          encodedString: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.keystore"
          encodedString: ${{ secrets.STOREFILE }}

      - name: Decode Google API key Json File
        uses: timheuer/base64-to-file@v1
        id: google_api_json_key
        with:
          fileName: "google_api_json_key.json"
          encodedString: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}

      - name: Configure App
        working-directory: ./
        run: |
          ./shMakefile appetizer-configure --env=hack
          ./shMakefile appetizer-version-bump


      - name: Deploy iOS to Firebase App Distribution
        working-directory: ./services/appetizer/ios
        run: |
          flutter pub get
          pod deintegrate
          pod update
          pod install --repo-update
          fastlane deploy_firebase --verbose
          fastlane add_plugin sentry --verbose
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.service_account_json_file.outputs.filePath }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          GOOGLE_CLOUD_PROJECT_ID: "heero-hack-412816"
          FASTLANE_APP_IOS_KEYS: "fastlane-app-ios-keys-hack"
          RELEASE_NOTES: ${{ steps.pr_title.outputs.result }}

      - name: Deploy Android to Firebase App Distribution
        working-directory: ./services/appetizer/android
        run: |
          fastlane deploy_firebase --verbose
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
          STORE_PASSWORD: ${{ secrets.STOREPASSWORD }}
          KEY_ALIAS: ${{ secrets.KEYALIAS}}
          KEY_PASSWORD: ${{ secrets.KEYPASSWORD }}
          ANDROID_JSON_KEY_FILE: ${{ steps.service_account_json_file.outputs.filePath }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.google_api_json_key.outputs.filePath }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          RELEASE_NOTES: ${{ steps.pr_title.outputs.result }}


      


      #- name: Send to Discord
      #  working-directory: ./
      #  run: |
      #    ./shMakefile appetizer-send-apk-to-discord --env=hack