name: "[Appetizer] - Release Prod"
on:
  workflow_dispatch: 
  push:
    tags:
      - "*"
    paths:
      - "services/appetizer/**"

env:
  AWS_REGION: eu-central-1

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      #- name: Update app version from configuration
      #  working-directory: ./
      #  run: |
      #    cp ./script/version_updater.sh ./version_updater.sh
      #    sh version_updater.sh

      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: service_account_json_file
        with:
          fileName: "serviceAccount.json"
          #encodedString: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON_PROD }}
          encodedString: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.keystore"
          encodedString: ${{ secrets.STOREFILE }}

      - name: Configure App
        working-directory: ./
        run: |
          ./shMakefile appetizer-configure --env=prod
          ./shMakefile appetizer-version-bump

      - name: Deploy iOS to TestFlight
        working-directory: ./services/appetizer/ios
        run: |
          flutter pub get
          pod deintegrate
          pod update
          pod install --repo-update
          fastlane deploy --verbose
          fastlane upload_symbols --verbose
          fastlane add_plugin sentry --verbose
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.service_account_json_file.outputs.filePath }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          #GOOGLE_CLOUD_PROJECT_ID: "heero-prod-412816"
          #FASTLANE_APP_IOS_KEYS: "fastlane-app-ios-keys"
          GOOGLE_CLOUD_PROJECT_ID: "heero-hack-412816"
          FASTLANE_APP_IOS_KEYS: "fastlane-app-ios-keys-hack"
      - name: Deploy Android
        working-directory: ./services/appetizer/android
        run: |
          fastlane deploy_store --verbose
        env:
          KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
          STORE_PASSWORD: ${{ secrets.STOREPASSWORD }}
          KEY_ALIAS: ${{ secrets.KEYALIAS}}
          KEY_PASSWORD: ${{ secrets.KEYPASSWORD }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.service_account_json_file.outputs.filePath }}
     