name: "[Kargo] - Build & Deploy"

on:
  push:
    tags:
      - '**'
    branches:
      - main
    paths:
      - "services/kargo/**"
      - "common/httpserver/**"
      - "common/talktome/**"
  pull_request:
    branches: ["**"]
    paths:
      - "services/kargo/**"
      - "common/httpserver/**"
      - "common/talktome/**"  

env:
  CICD_GITBRANCH: ${{ github.head_ref }}

jobs:  
  terraform-infra-hack:
    name: Terraform Drift
    uses: ./.github/workflows/kubeservice-test-terraform.yaml
    secrets: inherit
    with:
      service: kargo
      environment: hack
  terraform-infra-prod:
    name: Terraform Drift
    uses: ./.github/workflows/kubeservice-test-terraform.yaml
    secrets: inherit
    with:
      service: kargo
      environment: prod

  test:
    name: Test
    uses: ./.github/workflows/kubeservice-test.yaml
    secrets: inherit
    with:
      service: kargo
      environment: hack

  push-hack:
    name: Build & Push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: 
      - test
    uses: ./.github/workflows/kubeservice-build.yaml
    secrets: inherit
    with:
      service: kargo
      environment: hack

  deploy-hack:
    name: Deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - push-hack
    uses: ./.github/workflows/kubeservice-deploy.yaml
    secrets: inherit
    with:
      service: kargo
      environment: hack
      
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: 'read'
#      id-token: 'write'
#    steps:
#      - uses: actions/checkout@v4
#      - uses: FedericoCarboni/setup-ffmpeg@v3
#      - name: Set up Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: '1.21'
#      - name: 'Authenticate to Google Cloud with kargo service account'
#        uses: 'google-github-actions/auth@v2'
#        with:
#          project_id: 'heero-hack-412816'
#          workload_identity_provider: 'projects/804148525421/locations/global/workloadIdentityPools/cicd-pipeline/providers/github'
#          service_account: 'kargo-hack@heero-hack-412816.iam.gserviceaccount.com'
#      - name: run test
#        run: ./shMakefile test-kargo
#
#  build:
#    runs-on: ubuntu-latest
#    needs:
#      - test
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: '1.21'
#      - name: build Kargo
#        run: ./shMakefile build-kargo
#
#  deploy-hack:
#    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_env == 'hack' }}
#    permissions:
#      contents: 'read'
#      id-token: 'write'
#    needs:
#      - test
#      - build
#    environment: heero-hack
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-go@v5
#        with:
#          go-version: '1.21'
#      - name: 'Authenticate to Google Cloud with kargo service account'
#        uses: 'google-github-actions/auth@v2'
#        with:
#          project_id: 'heero-hack-412816'
#          workload_identity_provider: 'projects/804148525421/locations/global/workloadIdentityPools/cicd-pipeline/providers/github'
#          service_account: 'cicd-github@heero-hack-412816.iam.gserviceaccount.com'
#
#      - name: 'Set up Cloud SDK'
#        uses: 'google-github-actions/setup-gcloud@v2'
#      - name: deploy
#        env:
#          CICD_JOBID: ${{ github.run_number }}
#        run: |-
#          gcloud auth configure-docker europe-west4-docker.pkg.dev
#          ./shMakefile deploy-kargo --env=hack
#
#  deploy-prod:
#    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_env == 'prod' }}
#    permissions:
#      contents: 'read'
#      id-token: 'write'
#    needs:
#      - test
#      - build
#    environment: heero-prod
#    runs-on: ubuntu-latest
#    steps:
#      - name: Wait for 5 minutes
#        run: sleep 300
#      - uses: actions/checkout@v4
#      - uses: actions/setup-go@v5
#        with:
#          go-version: '1.21'
#      - name: 'Authenticate to Google Cloud with kargo service account'
#        uses: 'google-github-actions/auth@v2'
#        with:
#          project_id: 'heero-hack-412816'
#          workload_identity_provider: 'projects/460392105513/locations/global/workloadIdentityPools/cicd-pipeline/providers/github'
#          service_account: 'cicd-github@heero-prod-412816.iam.gserviceaccount.com'
#
#      - name: 'Set up Cloud SDK'
#        uses: 'google-github-actions/setup-gcloud@v2'
#
#      - name: deploy
#        env:
#          CICD_JOBID: ${{ github.job }}
#        run: |-
#          gcloud auth configure-docker europe-west4-docker.pkg.dev
#          ./shMakefile deploy-kargo --env=prod
#
#      - name: deployabot
#        run: 'curl  -H "Content-Type:application/json" -X POST -d "{\"username\": \"[shMakefile] DeployaBot\", \"content\": \" :tropical_fish: A new version of **kargo** has been released to **heero-prod**! :tropical_fish: \nSee ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" https://discord.com/api/webhooks/1214603564916146196/Nj7dBuCHU9LI49GSRq6HJjiOCzVl2qcKokIZu9Mw28g0UaE4CjgZi6JJZsC0gXcbDvir'
