{
 "title": "brocadue - service",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PubSub Grammar - Backlog",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "aliasBy": "kpi_grammar",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "brocadue-conversation_messages_kpi_grammar",
       "AND",
       "metric.type",
       "=",
       "pubsub.googleapis.com/subscription/backlog_bytes"
      ],
      "groupBys": [ "resource.label.subscription_id" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "heero-hack-412816",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "kpi_speech",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "brocadue-conversation_messages_kpi_speech",
       "AND",
       "metric.type",
       "=",
       "pubsub.googleapis.com/subscription/backlog_bytes"
      ],
      "groupBys": [ "resource.label.subscription_id" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "heero-hack-412816",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "PubSub Grammar - Unacked",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "aliasBy": "kpi_grammar",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "brocadue-conversation_messages_kpi_grammar",
       "AND",
       "metric.type",
       "=",
       "pubsub.googleapis.com/subscription/num_unacked_messages_by_region"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "heero-hack-412816",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "kpi_speech",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "brocadue-conversation_messages_kpi_speech",
       "AND",
       "metric.type",
       "=",
       "pubsub.googleapis.com/subscription/num_unacked_messages_by_region"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "heero-hack-412816",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "PubSub Grammar - Oldest Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "aliasBy": "kpi_grammar",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "brocadue-conversation_messages_kpi_grammar",
       "AND",
       "metric.type",
       "=",
       "pubsub.googleapis.com/subscription/oldest_unacked_message_age"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "heero-hack-412816",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "kpi_speech",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "brocadue-conversation_messages_kpi_speech",
       "AND",
       "metric.type",
       "=",
       "pubsub.googleapis.com/subscription/oldest_unacked_message_age"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "heero-hack-412816",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {cluster=\"arn:aws:eks:eu-west-1:767398121280:cluster/heero-hack\",namespace=\"brocadue\"} \n        |= \"error\"\n        [$__auto]\n    )\n)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{cluster=\"arn:aws:eks:eu-west-1:767398121280:cluster/heero-hack\",namespace=\"brocadue\"} |= \"error\"\n        "
    }
   ]
  },
  {
   "title": "Links",
   "type": "text",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 15 },
   "options": {
    "content": "* [Explore Logs](https://grafana.hack2.heero.me/explore?schemaVersion=1&panes=%7B%22b52%22:%7B%22datasource%22:%22loki-heero-grafanacloud%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22arn:aws:eks:eu-west-1:767398121280:cluster%2Fheero-hack%5C%22,namespace%3D%5C%22brocadue%5C%22%7D%20%5Cn%7C%3D%20%5C%22error%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki-heero-grafanacloud%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1)"
   }
  },
  {
   "title": "Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"brocadue\", container!=\"\"}) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"brocadue\", resource=\"cpu\"}\n)\n",
       "legendFormat": "requests"
      },
      {
       "expr": "max(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"brocadue\", resource=\"cpu\"}\n)\n",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"brocadue\"})by(phase)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pos Restarts",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum by (pod) (increase(kube_pod_container_status_restarts_total{pod=~\"brocadue-.*\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage (WSS)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",  namespace=\"brocadue\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\",  namespace=\"brocadue\",  resource=\"memory\"}\n)\n",
       "legendFormat": "requests"
      },
      {
       "expr": "max(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\",  namespace=\"brocadue\",  resource=\"memory\"}\n)\n",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"brocadue\", container!=\"\"}[$__rate_interval])) by (pod,container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"brocadue\", container!=\"\"}[$__rate_interval])) by (pod,container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",  namespace=\"brocadue\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",  namespace=\"brocadue\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",  namespace=\"brocadue\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Received Packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",  namespace=\"brocadue\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",  namespace=\"brocadue\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Received Packets Dropped",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",  namespace=\"brocadue\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}