on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      environment:
        required: true
        type: string
permissions:
  id-token: write
  contents: read
      
env:
  HEERO_AWS_ACCOUNT_ID: ${{ inputs.environment == 'prod' && '654654538697' || '767398121280' }}
  HEERO_GCLOUD_IDP: ${{ inputs.environment == 'prod' && 'projects/460392105513/locations/global/workloadIdentityPools/cicd-pipeline/providers/github' || 'projects/804148525421/locations/global/workloadIdentityPools/cicd-pipeline/providers/github' }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:   
  unit:
    runs-on: arm-bubuntu-8
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6.0.2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@main
        with:
          terraform_version: latest
          terraform_wrapper: 'true'
          
      - name: Authenticate to Google Cloud with service service-account
        uses: google-github-actions/auth@v3
        with:
          project_id: 'heero-${{ inputs.environment }}-412816'
          workload_identity_provider: '${{ env.HEERO_GCLOUD_IDP }}'
#          service_account: 'cicd-github@heero-${{ inputs.environment }}-412816.iam.gserviceaccount.com'
          service_account: '${{ inputs.service }}-${{ inputs.environment }}@heero-${{ inputs.environment }}-412816.iam.gserviceaccount.com'

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: "arn:aws:iam::${{ env.HEERO_AWS_ACCOUNT_ID }}:role/github-action"  
        
      - name: Set up Java 21 (thanks broca)
        run: echo "JAVA_HOME=${JAVA_HOME_21_X64}" >> $GITHUB_ENV

#      - name: Set up FFmpeg (thanks Kargo)
#        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: run unit tests
        run: ./shMakefile test-kubeservice --env=local --service=${{ inputs.service }}