apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rea.fullname" . }}
  labels:
    {{- include "rea.labels" . | nindent 4 }}
data:
  # property-like keys; each key maps to a simple value
  config.yaml: |
    {{ .Values.rea.config | nindent 4 }}
  