apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rea.fullname" . }}-gcloud
type: opaque
data:
  {{/* The supplied value is already encoded in b64 */}}
  google-credentials.json: {{ .Values.googleCredentials | quote }}
  